### ISSUE TITLE
Create an RSS feed

### ISSUE THREAD

**Issue by hankchizljaw** [hankchizljaw/educationlinks.fyi#2]
A feed of items would be great. A good starting point would be the one from [Hylia](https://github.com/hankchizljaw/hylia/blob/master/src/feed.njk).

Make sure it's linked up in the `<head>` too!

**Comment by borntofrappe** [comment]
Good day @hankchizljaw. I'm fairly new to eleventy and nunjuck, but I'd like to help.

Let me know if this is possible.

**Comment by hankchizljaw** [comment]
That would be great, thank you :)

**Comment by hankchizljaw** [comment]
Solved with #13
